# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_chasis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('installation_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[('CASH', 'Cash'), ('BANK DEPOSIT', 'Bank Deposit'), ('CHEQUE', 'Cheque'), ('RTGS', 'RTGS')], max_length=20)),
                ('name_payer', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
    ]
