# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160210_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_chasis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('installation_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_chasis_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_registration_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 15, 20, 50, 37, 581926, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 20, 50, 49, 784772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer'),
        ),
    ]
