# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160427_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_chasis_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
